# Site settings
author: Ann Marie
title: The Art of the Science of Data
header-img: img/home-bg.png
email: 40plusalive@gmail.com
copyright_name: Ann Marie
description: > # this means to ignore newlines until "baseurl:"
  Why I joined a Data Science Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AnnMarie201

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
